services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "16G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      GPU: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/dri
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - /var/dsm:/storage
    restart: always
    stop_grace_period: 2m