
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "16G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      GPU: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/dri
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - /var/dsm:/storage
    restart: always
    stop_grace_period: 2m
    
    networks:
      - tipi_main_network

    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.dsm-web-redirect.redirectscheme.scheme: https
      traefik.http.services.dsm.loadbalancer.server.port: 5000
      # Web
      traefik.http.routers.dsm-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dsm-insecure.entrypoints: web
      traefik.http.routers.dsm-insecure.service: dsm
      traefik.http.routers.dsm-insecure.middlewares: dsm-web-redirect
      # Websecure
      traefik.http.routers.dsm.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dsm.entrypoints: websecure
      traefik.http.routers.dsm.service: dsm
      traefik.http.routers.dsm.tls.certresolver: myresolver
