version: "3.7"
services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: "Shares"
      USER: "altan"
      PASS: "altan"
      RW: "false"
    ports:
      - 445:445
    volumes:
      - /home/altan/runtipi/media:/storage
      - /home/altan/runtipi/user-config/users.conf:/etc/samba/users.conf
    labels:
      runtipi.managed: true
