version: "3.7"
services:
  samba:
    image: dockurr/samba:4.21.3
    container_name: samba
    environment:
      NAME: "Shares"
      USER: "altan"
      PASS: "altan"
      RW: "true"
    ports:
      - 445:445
    volumes:
      - /home/altan/runtipi/media/data:/storage

    labels:
      runtipi.managed: true
