version: "3.7"
services:
  zerotier:
    container_name: zerotier
    image: zyclonite/zerotier
    restart: always
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    network_mode: host
    labels:
      runtipi.managed: true
